version: "3"
services:
  mongo:
    image: "mongo"
    restart: always
  redis:
    image: "redis:latest"
    restart: always
  api:
    restart: always
    build:
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_URI=mongodb://mongo:27017/chat-rooms
